import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Activity, Bot, BriefcaseBusiness, Check, ChevronRight, CircleAlert, Clock3, FileText, LayoutDashboard, LoaderCircle, Plus, RefreshCw, Settings, ShieldCheck, UserRound, X } from 'lucide-react'
import './App.css'

const apiBaseUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000/api/v1'
type Metric = Record<string, number>
type Run = { id: number; status: string; created_at: string }
type Job = { id: number; run_id: number; domain: string; state: string; checkpoint: string; retry_count: number; url: string; current_url?: string; updated_at: string }
type Question = { id: number; label: string; field_type: string; reason: string; suggested_answer: string; status: string }
type Dashboard = { runs: Run[]; metrics: Metric }
type JobDetail = { job: Job; events: { id: number; detail: string; created_at: string; to_state: string }[]; blocked_questions: Question[] }
const navItems = [['Overview', LayoutDashboard], ['Application Queue', BriefcaseBusiness], ['Review Inbox', CircleAlert], ['Profile', UserRound], ['Automation', Bot], ['Settings', Settings]] as const

function api<T>(path: string, options?: RequestInit): Promise<T> {
  return fetch(`${apiBaseUrl}${path}`, { headers: { 'Content-Type': 'application/json' }, ...options }).then(async (response) => {
    if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail ?? 'Request failed')
    return response.json() as Promise<T>
  })
}

function App() {
  const [page, setPage] = useState<(typeof navItems)[number][0]>('Overview')
  const [dashboard, setDashboard] = useState<Dashboard | null>(null)
  const [run, setRun] = useState<{ run: Run; jobs: Job[] } | null>(null)
  const [selectedJob, setSelectedJob] = useState<JobDetail | null>(null)
  const [profile, setProfile] = useState('{}')
  const [urls, setUrls] = useState('')
  const [notice, setNotice] = useState('')
  const [loading, setLoading] = useState(true)
  const refresh = async () => { setLoading(true); try { const result = await api<Dashboard>('/dashboard'); setDashboard(result); if (!run && result.runs[0]) await selectRun(result.runs[0].id) } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to reach the API') } finally { setLoading(false) } }
  const selectRun = async (runId: number) => { try { setRun(await api<{ run: Run; jobs: Job[] }>(`/runs/${runId}`)) } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to load run') } }
  const selectJob = async (jobId: number) => { try { setSelectedJob(await api<JobDetail>(`/jobs/${jobId}`)) } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to load job') } }
  useEffect(() => { void refresh() }, [])
  useEffect(() => { if (page === 'Profile') api<object>('/profile').then((data) => setProfile(JSON.stringify(data, null, 2))).catch(() => undefined) }, [page])
  const createRun = async (event: FormEvent) => { event.preventDefault(); try { const created = await api<Run>('/runs', { method: 'POST', body: JSON.stringify({ urls: urls.split('\n').filter(Boolean) }) }); setUrls(''); setNotice(`Run #${created.id} created.`); await refresh(); await selectRun(created.id); setPage('Application Queue') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to create run') } }
  const metrics = dashboard?.metrics ?? {}; const jobs = run?.jobs ?? []
  return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">A</span>Apply<span>Stack</span></div><div className="workspace">WORKSPACE <ChevronRight size={13} /></div><nav>{navItems.map(([label, Icon]) => <button key={label} className={page === label ? 'nav active' : 'nav'} onClick={() => setPage(label)}><Icon size={18} />{label}{label === 'Review Inbox' && metrics.needs_review > 0 && <b>{metrics.needs_review}</b>}</button>)}</nav><div className="sidebar-foot"><ShieldCheck size={17} /><span>Review-only mode<br /><small>Submission is disabled</small></span></div></aside><section className="content"><header><div><p className="eyebrow">JOB APPLICATION OPERATIONS</p><h1>{page}</h1></div><div className="header-actions"><span className="live"><i /> API online</span><button className="icon-button" title="Refresh data" onClick={() => void refresh()}><RefreshCw size={17} /></button><button className="avatar" title="Profile">AD</button></div></header>{notice && <div className="notice"><span>{notice}</span><button title="Dismiss notice" onClick={() => setNotice('')}><X size={16} /></button></div>}
  {page === 'Overview' && <><section className="metric-grid"><Metric label="Queue" value={metrics.queued} caption="applications waiting" icon={<Clock3 />} tone="blue" /><Metric label="Preparing" value={metrics.preparing} caption="visible browser sessions" icon={<LoaderCircle />} tone="orange" /><Metric label="Needs review" value={metrics.needs_review} caption="blocked questions" icon={<CircleAlert />} tone="red" /><Metric label="Ready" value={metrics.ready_for_review} caption="prepared, never submitted" icon={<Check />} tone="green" /></section><section className="two-column"><div className="panel intake"><div className="panel-heading"><div><p className="eyebrow">NEW WORK</p><h2>Start an application run</h2></div><Plus size={20} /></div><form onSubmit={createRun}><label>Direct application URLs<textarea value={urls} onChange={(event) => setUrls(event.target.value)} placeholder={'https://jobs.company.com/role\nhttps://boards.greenhouse.io/company/jobs/...'} /></label><button className="primary" type="submit"><Plus size={17} /> Create safe review run</button></form><p className="hint">The agent fills verified profile data and stops before final submission.</p></div><div className="panel"><div className="panel-heading"><div><p className="eyebrow">TODAY</p><h2>Operational pulse</h2></div><Activity size={20} /></div><div className="pulse"><span>LLM spend</span><strong>${Number(metrics.llm_spend_today ?? 0).toFixed(4)}</strong><small>of ${Number(metrics.llm_daily_budget ?? 1).toFixed(2)} daily budget</small><div className="budget"><i style={{ width: `${Math.min(100, 100 * Number(metrics.llm_spend_today ?? 0) / Number(metrics.llm_daily_budget ?? 1))}%` }} /></div></div><div className="run-list">{(dashboard?.runs ?? []).slice(0, 4).map((item) => <button key={item.id} onClick={() => { void selectRun(item.id); setPage('Application Queue') }}><span><b>Run #{item.id}</b><small>{new Date(item.created_at).toLocaleString()}</small></span><em>{item.status}</em></button>)}{!dashboard?.runs.length && <p className="empty">No application runs yet.</p>}</div></div></section></>}
  {(page === 'Application Queue' || page === 'Review Inbox') && <section className="workspace-grid"><div className="panel run-panel"><div className="panel-heading"><div><p className="eyebrow">APPLICATIONS</p><h2>{run ? `Run #${run.run.id}` : 'Select a run'}</h2></div><select value={run?.run.id ?? ''} onChange={(event) => void selectRun(Number(event.target.value))}><option value="">Runs</option>{dashboard?.runs.map((item) => <option key={item.id} value={item.id}>Run #{item.id}</option>)}</select></div><div className="job-list">{jobs.filter((job) => page === 'Application Queue' || job.state.startsWith('waiting')).map((job) => <button className={selectedJob?.job.id === job.id ? 'job selected' : 'job'} onClick={() => void selectJob(job.id)} key={job.id}><span className={`status ${job.state}`} /><span className="job-copy"><b>{job.domain}</b><small>#{job.id} · {job.state.replaceAll('_', ' ')}</small></span><ChevronRight size={17} /></button>)}{!jobs.length && <p className="empty">Create or select a run to inspect its applications.</p>}</div></div><JobPanel detail={selectedJob} onRefresh={selectJob} onNotice={setNotice} /></section>}
  {page === 'Profile' && <section className="profile-layout"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">CANDIDATE RECORD</p><h2>Profile source of truth</h2></div><FileText size={20} /></div><p className="hint">This document supplies evidence-backed details to the form resolver.</p><textarea className="profile-editor" value={profile} onChange={(event) => setProfile(event.target.value)} spellCheck="false" /><button className="primary" onClick={async () => { try { await api('/profile', { method: 'PUT', body: profile }); setNotice('Profile saved.') } catch { setNotice('Profile must be valid JSON.') } }}><Check size={17} /> Save profile</button></div><div className="panel profile-side"><p className="eyebrow">DATA POLICY</p><h2>Human stays in control</h2><ul className="policy"><li><Check size={16} /> Uses approved facts only</li><li><Check size={16} /> Saves reusable answers with approval</li><li><Check size={16} /> Never submits applications</li></ul></div></section>}
  {(page === 'Automation' || page === 'Settings') && <section className="panel settings-panel"><p className="eyebrow">CONFIGURATION</p><h2>{page === 'Automation' ? 'Automation guardrails' : 'Service settings'}</h2><Setting icon={<Bot size={20} />} name="Review-only submission policy" value="Portal preparation stops before final submit." /><Setting icon={<Activity size={20} />} name="API base URL" value={apiBaseUrl} /><Setting icon={<Settings size={20} />} name="Runtime configuration" value="Host, CORS, storage, and LLM credentials use environment variables." /></section>}{loading && <div className="loading"><LoaderCircle size={18} /> Syncing workspace</div>}</section></main>
}
function Metric({ label, value = 0, caption, icon, tone }: { label: string; value?: number; caption: string; icon: React.ReactNode; tone: string }) { return <article className={`metric ${tone}`}><div className="metric-icon">{icon}</div><p>{label}</p><strong>{value}</strong><small>{caption}</small></article> }
function Setting({ icon, name, value }: { icon: React.ReactNode; name: string; value: string }) { return <div className="setting-row">{icon}<div><b>{name}</b><small>{value}</small></div><span className="enabled">Enforced</span></div> }
function JobPanel({ detail, onRefresh, onNotice }: { detail: JobDetail | null; onRefresh: (id: number) => Promise<void>; onNotice: (message: string) => void }) { if (!detail) return <aside className="panel detail empty-detail"><BriefcaseBusiness size={28} /><h2>Select an application</h2><p>Inspect form progress and review questions.</p></aside>; const approve = async (question: Question, answer: string) => { try { await api(`/questions/${question.id}/approve`, { method: 'POST', body: JSON.stringify({ answer, scope: 'profile_reusable' }) }); await onRefresh(detail.job.id); onNotice('Answer approved and saved for reuse.') } catch (error) { onNotice(error instanceof Error ? error.message : 'Could not approve answer') } }; return <aside className="panel detail"><div className="panel-heading"><div><p className="eyebrow">APPLICATION #{detail.job.id}</p><h2>{detail.job.domain}</h2></div><span className="state-chip">{detail.job.state.replaceAll('_', ' ')}</span></div><a href={detail.job.current_url ?? detail.job.url} target="_blank" rel="noreferrer">Open application page</a>{detail.blocked_questions.filter((q) => q.status === 'pending').map((question) => <Question key={question.id} question={question} approve={approve} />)}<section className="timeline"><h3>Activity log</h3>{detail.events.slice().reverse().slice(0, 5).map((event) => <div key={event.id}><span /><p><b>{event.to_state.replaceAll('_', ' ')}</b>{event.detail}<small>{new Date(event.created_at).toLocaleString()}</small></p></div>)}</section></aside> }
function Question({ question, approve }: { question: Question; approve: (question: Question, answer: string) => Promise<void> }) { const [answer, setAnswer] = useState(question.suggested_answer); return <section className="question"><h3>{question.label}</h3><small>{question.reason}</small>{question.field_type === 'radio' ? <select value={answer || 'Yes'} onChange={(e) => setAnswer(e.target.value)}><option>Yes</option><option>No</option></select> : <textarea value={answer} onChange={(e) => setAnswer(e.target.value)} placeholder="Enter approved answer" />}<button className="small-primary" onClick={() => void approve(question, answer)}><Check size={14} /> Approve</button></section> }
export default App